### PR TITLE
Bug Fixes

### PR DESCRIPTION
**Pull request by dtjones190**
My system was reaching unreachable code because of a bug, changed to pass an error instead of panicking.
Fixed the error in calculating PDU length for write_multiple for TCP

### CODE REVIEW

**Comment by flosse** [comment]
Thanks for your PR!
Would you mind to do a rebase?

**Comment by dtjones190** [comment]
> Thanks for your PR!
> Would you mind to do a rebase?

Done. Looks like CI failed because cargo was not able to update itself though.

**Comment by flosse** [comment]
@dtjones190 sorry for not taking care of this for such a long time.
I hopefully will manage to take a second look at it within the next days.

**Comment by flosse** [comment]
@dtjones190 I'd release a v0.1.0 if you don't mind?

**Pull request merged**
